name: Terraform Azure Deployment

on:
  push:
    branches:
      - feature/github-pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ 3f86a4c1-6e37-4bcd-b0c3-2bf20b305eb2 }}
          tenant-id: ${{ 1ce567c7-283d-4272-b4bd-8292e9e4cd20 }}
          subscription-id: ${{ 617408c3-ce8d-4f34-a887-db4cd7d25b4e }}

      - name: Terraform Init
        working-directory: environment
        run: terraform init

      - name: Terraform Plan
        working-directory: environment
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: environment
        run: terraform apply -auto-approve tfplan